version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #See https://docs.aws.amazon.com/codebuild/latest/userguide/sample-runtime-versions.html for available runtimes
    runtime-versions:
       ruby: 2.6
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       - aws s3 cp s3://${bucket_name}/task_def.json .
       - aws s3 cp s3://${bucket_name}/appspec.yml .
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - task_def.json
    - appspec.yml
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths